### ISSUE TITLE
Feature: User can add a pokemon

### ISSUE THREAD

**Issue by kyle-foral** [kyle-foral/AJAX-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged? 

User can add a pokemon to the party.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allows the user to search and select a pokemon of their choosing to place into their party.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/126129416/234138820-c766bb24-4296-4729-af16-b46b73af16ce.png)
![image](https://user-images.githubusercontent.com/126129416/234138860-37f5f104-1176-4038-a3fe-94cf73463a75.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create a form.
- [x] Place HTML in code to match layout for desktop.
- [x] Apply CSS to make sure both phone and desktop have correct layout.
- [x] Make sure all inputs are required for each pokemon slot.
- [x] Make image of the card load for the pokemon that was entered.
- [x] Follow for all party slots.
- [x] Make sure 'submit' button only works when all party slots are full.
- [x] Put the values of the party in an array.
- [x] Make sure each party has it's own unique ID.
- [x] Make sure the next party has a new unique ID.
- [x] Reset images and names of pokemon.
- [x] #6
- [x] Make sure the party stays loaded even on page refresh.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
