### ISSUE TITLE
Feature: User can view party

### ISSUE THREAD

**Issue by kyle-foral** [kyle-foral/AJAX-Project#2]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?

User can view their party.

## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.

Allows the user to see the parties they have created.

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/126129416/234133425-37548dcf-0359-4f7f-8df4-59647ef052e2.png)
![image](https://user-images.githubusercontent.com/126129416/234133490-5cdee09b-44fd-42ee-aca2-7ba4ffcc73f3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ...
- [x] Make an new view page in the HTML
- [x] Add an empty uL for the entries to be placed into and loaded from local storage.
- [x] Adjust the view page to work on desktop and mobile devices.
- [x] Make a new function with one parameter (entry) so the entry, that creates all the elements for the HTML page and returns the top element that will be appended.
- [x] Create an event listener to the document object that will listen for when the pages 'loads'. This event listener will have a callback function to append each entry in the local storage.
- [x] Make a new function that will swap between the two pages of "card-pick' and the view page.
- [x] Have the 'View' anchor at the top of the page load the view page.
- [x] Have the 'Add' anchor swap back to the 'card-pick' page.
- [x] Update the submit button to correctly swap between the pages when a new party is saved.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
