### ISSUE TITLE
Feature: User can Edit Party

### ISSUE THREAD

**Issue by kyle-foral** [kyle-foral/AJAX-Project#3]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?

User can edit a party.

## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.

Allows the user to edit their party by changing the pokemon inside and swapping with a new one.

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/126129416/234133721-10670306-4050-4506-8104-13618b1904fe.png)
![image](https://user-images.githubusercontent.com/126129416/234133770-a1da2b37-a996-4bd1-905a-219955db8498.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] ...
- [x] Add a new button next to the party title on view page that allows me to edit the party it selects.
- [x] Upon clicking on the edit button it will swap back to the add page, but with the party already loaded so you can allow changes to be made.
- [x] Make the sure party loaded entry ID matches the one clicked on.
- [x] When saving the edited party.
- [x] Make sure it doesn't create a new entry.
- [x] Have it replace the entry ID that is selected.
- [x] Use the function to swap pages back to view page.
- [x] Append back to the view page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
