### ISSUE TITLE
Feature: User can Delete a party

### ISSUE THREAD

**Issue by kyle-foral** [kyle-foral/AJAX-Project#4]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?

User can delete on of their parties.

## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.

Allows the user to remove a party slot deleting the pokemon inside.

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/126129416/234133974-55675361-34dd-4c9e-b642-43130f5266dc.png)
![image](https://user-images.githubusercontent.com/126129416/234133999-0e9a8ae5-ff95-4e49-9b0f-beeb68af8c06.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

- [x] ...
- [x] Add a delete anchor on the "Add" page.
- [x] Make a pop up for when the user wants to delete a pokemon party.
- [x] Clicking "No" will remove the pop up.
- [x] Clicking "Yes" will remove a pokemon party.
- [x] Make sure that the correct pokemon party gets removed.
- [x] Remove the pop up.
- [x] Swap pages back to the the "View" page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
