### ISSUE TITLE
Feature: User can Favorite a party

### ISSUE THREAD

**Issue by kyle-foral** [kyle-foral/AJAX-Project#5]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?

User can favorite a party.

## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.

Allows the user to favorite a pokemon party which will put a star next to the party name.

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/126129416/236268127-fc3ea102-fda3-42a8-bfc8-09526d3ea8c4.png)
![image](https://user-images.githubusercontent.com/126129416/236268279-dd9f0eda-4c1c-45ec-b4b4-37d9bb8b1788.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ...
- [x] Create a star icon to the left of the party title on the view page.
- [x] Give the star icon an addEventListener.
- [x] Allow the star to become clickable.
- [x] Make the star toggle between 2 colors (starting on black.)
- [x] On click turn the star yellow indicating that the party has become a favorite.
- [x] On click again when already yellow turn the star black indicating the party is no longer a favorite.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
